import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-professional-services-sow-revenue-leakage",
  "engine": "recovery",
  "title": "Professional Services SOW Revenue Leakage",
  "shortTitle": "Professional Services SOW Revenue Leakage",
  "tagline": "Capture unbilled services, milestones, expenses, scope changes, and contractual price adjustments.",
  "industry": "Professional Services Revenue Assurance",
  "buyer": "Consulting, implementation, and managed-service firms",
  "uiPort": 4727,
  "apiPort": 5727,
  "accent": "#15803d",
  "currency": "USD",
  "primaryOutcome": "Professional Services SOW Revenue Leakage converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect MSAs, SOWs, milestones, resources, time, expenses, deliverables, change requests, acceptance, invoices, and collections in one accountable workflow. Capture unbilled services, milestones, expenses, scope changes, and contractual price adjustments.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Professional Services SOW Revenue Leakage evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("msa-sow-library","PSS01","MSA SOW library","Execute msa sow library using MSAs, SOWs, milestones, resources, time, expenses, deliverables, change requests, acceptance, invoices, and collections.","Produce a governed msa sow library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Client / Statement of Work","text","Client / Statement of Work · Standard Case"],["caseReference","MSA SOW library Reference","text","PSS01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1662500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2011625],["domainDriver","Billing Model","select","Time and materials",["Time and materials","Fixed fee","Milestone"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["MSA SOW library case","Resource rate card case","Time entry ingestion case","Expense eligibility case","Milestone completion evidence case"]}),
feature("resource-rate-card","PSS02","Resource rate card","Execute resource rate card using MSAs, SOWs, milestones, resources, time, expenses, deliverables, change requests, acceptance, invoices, and collections.","Produce a governed resource rate card decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Client / Statement of Work","text","Client / Statement of Work · Standard Case"],["caseReference","Resource rate card Reference","text","PSS02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1662500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2011625],["domainDriver","Billing Model","select","Time and materials",["Time and materials","Fixed fee","Milestone"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["MSA SOW library case","Resource rate card case","Time entry ingestion case","Expense eligibility case","Milestone completion evidence case"]}),
feature("time-entry-ingestion","PSS03","Time entry ingestion","Execute time entry ingestion using MSAs, SOWs, milestones, resources, time, expenses, deliverables, change requests, acceptance, invoices, and collections.","Produce a governed time entry ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Client / Statement of Work","text","Client / Statement of Work · Standard Case"],["caseReference","Time entry ingestion Reference","text","PSS03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1662500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2011625],["domainDriver","Billing Model","select","Time and materials",["Time and materials","Fixed fee","Milestone"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["MSA SOW library case","Resource rate card case","Time entry ingestion case","Expense eligibility case","Milestone completion evidence case"]}),
feature("expense-eligibility","PSS04","Expense eligibility","Execute expense eligibility using MSAs, SOWs, milestones, resources, time, expenses, deliverables, change requests, acceptance, invoices, and collections.","Produce a governed expense eligibility decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Client / Statement of Work","text","Client / Statement of Work · Standard Case"],["caseReference","Expense eligibility Reference","text","PSS04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1662500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2011625],["domainDriver","Billing Model","select","Time and materials",["Time and materials","Fixed fee","Milestone"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["MSA SOW library case","Resource rate card case","Time entry ingestion case","Expense eligibility case","Milestone completion evidence case"]}),
feature("milestone-completion-evidence","PSS05","Milestone completion evidence","Execute milestone completion evidence using MSAs, SOWs, milestones, resources, time, expenses, deliverables, change requests, acceptance, invoices, and collections.","Produce a governed milestone completion evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Client / Statement of Work","text","Client / Statement of Work · Standard Case"],["caseReference","Milestone completion evidence Reference","text","PSS05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1662500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2011625],["domainDriver","Billing Model","select","Time and materials",["Time and materials","Fixed fee","Milestone"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["MSA SOW library case","Resource rate card case","Time entry ingestion case","Expense eligibility case","Milestone completion evidence case"]}),
feature("deliverable-acceptance-tracking","PSS06","Deliverable acceptance tracking","Execute deliverable acceptance tracking using MSAs, SOWs, milestones, resources, time, expenses, deliverables, change requests, acceptance, invoices, and collections.","Produce a governed deliverable acceptance tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Client / Statement of Work","text","Client / Statement of Work · Standard Case"],["caseReference","Deliverable acceptance tracking Reference","text","PSS06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1662500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2011625],["domainDriver","Billing Model","select","Time and materials",["Time and materials","Fixed fee","Milestone"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["MSA SOW library case","Resource rate card case","Time entry ingestion case","Expense eligibility case","Milestone completion evidence case"]}),
feature("fixed-fee-allocation","PSS07","Fixed-fee allocation","Execute fixed-fee allocation using MSAs, SOWs, milestones, resources, time, expenses, deliverables, change requests, acceptance, invoices, and collections.","Produce a governed fixed-fee allocation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Client / Statement of Work","text","Client / Statement of Work · Standard Case"],["caseReference","Fixed-fee allocation Reference","text","PSS07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1662500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2011625],["domainDriver","Billing Model","select","Time and materials",["Time and materials","Fixed fee","Milestone"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["MSA SOW library case","Resource rate card case","Time entry ingestion case","Expense eligibility case","Milestone completion evidence case"]}),
feature("time-material-billing","PSS08","Time-material billing","Execute time-material billing using MSAs, SOWs, milestones, resources, time, expenses, deliverables, change requests, acceptance, invoices, and collections.","Produce a governed time-material billing decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Client / Statement of Work","text","Client / Statement of Work · Standard Case"],["caseReference","Time-material billing Reference","text","PSS08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1662500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2011625],["domainDriver","Billing Model","select","Time and materials",["Time and materials","Fixed fee","Milestone"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["MSA SOW library case","Resource rate card case","Time entry ingestion case","Expense eligibility case","Milestone completion evidence case"]}),
feature("change-request-detection","PSS09","Change request detection","Execute change request detection using MSAs, SOWs, milestones, resources, time, expenses, deliverables, change requests, acceptance, invoices, and collections.","Produce a governed change request detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Client / Statement of Work","text","Client / Statement of Work · Standard Case"],["caseReference","Change request detection Reference","text","PSS09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1662500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2011625],["domainDriver","Billing Model","select","Time and materials",["Time and materials","Fixed fee","Milestone"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["MSA SOW library case","Resource rate card case","Time entry ingestion case","Expense eligibility case","Milestone completion evidence case"]}),
feature("out-of-scope-work-quantification","PSS10","Out-of-scope work quantification","Execute out-of-scope work quantification using MSAs, SOWs, milestones, resources, time, expenses, deliverables, change requests, acceptance, invoices, and collections.","Produce a governed out-of-scope work quantification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Client / Statement of Work","text","Client / Statement of Work · Standard Case"],["caseReference","Out-of-scope work quantification Reference","text","PSS10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1662500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2011625],["domainDriver","Billing Model","select","Time and materials",["Time and materials","Fixed fee","Milestone"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["MSA SOW library case","Resource rate card case","Time entry ingestion case","Expense eligibility case","Milestone completion evidence case"]}),
feature("price-escalation-control","PSS11","Price escalation control","Execute price escalation control using MSAs, SOWs, milestones, resources, time, expenses, deliverables, change requests, acceptance, invoices, and collections.","Produce a governed price escalation control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Client / Statement of Work","text","Client / Statement of Work · Standard Case"],["caseReference","Price escalation control Reference","text","PSS11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1662500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2011625],["domainDriver","Billing Model","select","Time and materials",["Time and materials","Fixed fee","Milestone"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["MSA SOW library case","Resource rate card case","Time entry ingestion case","Expense eligibility case","Milestone completion evidence case"]}),
feature("invoice-generation","PSS12","Invoice generation","Execute invoice generation using MSAs, SOWs, milestones, resources, time, expenses, deliverables, change requests, acceptance, invoices, and collections.","Produce a governed invoice generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Client / Statement of Work","text","Client / Statement of Work · Standard Case"],["caseReference","Invoice generation Reference","text","PSS12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1662500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2011625],["domainDriver","Billing Model","select","Time and materials",["Time and materials","Fixed fee","Milestone"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["MSA SOW library case","Resource rate card case","Time entry ingestion case","Expense eligibility case","Milestone completion evidence case"]}),
feature("client-dispute-workflow","PSS13","Client dispute workflow","Execute client dispute workflow using MSAs, SOWs, milestones, resources, time, expenses, deliverables, change requests, acceptance, invoices, and collections.","Produce a governed client dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Client / Statement of Work","text","Client / Statement of Work · Standard Case"],["caseReference","Client dispute workflow Reference","text","PSS13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1662500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2011625],["domainDriver","Billing Model","select","Time and materials",["Time and materials","Fixed fee","Milestone"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["MSA SOW library case","Resource rate card case","Time entry ingestion case","Expense eligibility case","Milestone completion evidence case"]}),
feature("cash-collection-tracking","PSS14","Cash collection tracking","Execute cash collection tracking using MSAs, SOWs, milestones, resources, time, expenses, deliverables, change requests, acceptance, invoices, and collections.","Produce a governed cash collection tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Client / Statement of Work","text","Client / Statement of Work · Standard Case"],["caseReference","Cash collection tracking Reference","text","PSS14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1662500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2011625],["domainDriver","Billing Model","select","Time and materials",["Time and materials","Fixed fee","Milestone"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["MSA SOW library case","Resource rate card case","Time entry ingestion case","Expense eligibility case","Milestone completion evidence case"]}),
feature("project-client-analytics","PSS15","Project client analytics","Execute project client analytics using MSAs, SOWs, milestones, resources, time, expenses, deliverables, change requests, acceptance, invoices, and collections.","Produce a governed project client analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Client / Statement of Work","text","Client / Statement of Work · Standard Case"],["caseReference","Project client analytics Reference","text","PSS15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1662500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2011625],["domainDriver","Billing Model","select","Time and materials",["Time and materials","Fixed fee","Milestone"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["MSA SOW library case","Resource rate card case","Time entry ingestion case","Expense eligibility case","Milestone completion evidence case"]})
]);
